#!/bin/bash
echo "=== CHECKING APPLIED FIXES ==="
echo ""
echo "Q1: Gemma-3 NaN fixes"
echo "  Layer 12: $(grep -A 3 'gemma3-1b' configs/gemma3-1b.yaml | grep layer)"
echo "  Safe norm: $(grep -A 2 'norm < 1e-8' src/steering/extract.py | head -1)"
echo "  FP32 upcast: $(grep 'activations.append(hidden.float())' src/steering/extract.py)"
echo ""
echo "Q3: MSE regularization"
echo "  MC trainer: $(grep 'mse_reg.*1e-2' src/steering/training.py | head -1)"
echo "  Gen trainer: $(grep 'mse_reg.*1e-2' src/steering/training.py | tail -1)"
echo ""
echo "Q4: Verbosity controls"
echo "  Temperature: $(grep 'temperature:' configs/base.yaml | grep 0.3)"
echo "  Max tokens: $(grep 'max_new_tokens: 64' configs/base.yaml)"
echo "  Stop sequences: $(grep 'stop_sequences:' configs/base.yaml)"
echo "  Judge tokens: $(grep 'max_new_tokens: 300' configs/base.yaml)"
echo ""
echo "=== MISSING FIXES ==="
echo "Q2: Vector/scale consistency - NOT IMPLEMENTED"
echo "  - No bank-sampled vector evaluation"
echo "  - No scale sweep (only scale=1.0 tested)"
echo ""
echo "Judge JSON failsafe - PARTIAL"
echo "  - Increased max_tokens to 300"
echo "  - No JSON repair logic in parser"
echo ""
echo "N2: Eval protocol - NOT IMPLEMENTED"
echo "  - No multiple vector sampling"
echo "  - No scale sweep"
echo "  - No greedy vs temp comparison"
