#!/usr/bin/env python3
"""Write every revision number the paper uses, straight from judged outputs.

Outputs (into --paper-dir, default paper/drafts/revision_oct2026/paper):
  numbers.tex          \\setres{key}{metric}{value} macros used by main.tex via \\res{key}{metric}
  categories_table.tex per-category T∧I table (App. C)
  lr_table.tex         full learning-rate table (App. E)
  cathold_table.tex    category hold-out table (App. G)
  gemma_table.tex      Gemma-3-4B-IT results (App. G)
  figures/lr_sweep.pdf learning-rate figure (Sec. 5.2)

Missing inputs simply leave their macros undefined (they render as red
placeholders), so the script can be re-run as results arrive.

Usage:
    python scripts/make_paper_numbers.py
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
import aggregate_revision as agg  # noqa: E402

OUT = Path("data/outputs")

# paper key -> rcv method name (aggregate_revision labels)
KEYS = {
    "base": "baseline", "caa1": "caa_a1", "caa2": "caa_a2", "mast": "mast",
    "dvzero": "dvzero_lr2e-3", "dvzerolow": "dvzero_lr5e-4", "dvzeroA": "dvzero_lr1e-3",
    "dvzerohigh": "dvzero_lr5e-3", "dvcaa": "dvcaa_lr5e-4", "dvcaahigh": "dvcaa_lr2e-3",
    "loradpo": "loradpo", "mastlrA": "mast_lr1e-3", "mastlrB": "mast_lr2e-3",
}
COMPARE = {  # macro key -> (a, b)
    "mastVcaa2": ("mast", "caa_a2"), "mastVlora": ("mast", "loradpo"),
    "mastVdvzero": ("mast", "dvzero_lr2e-3"), "mastVdvzlow": ("mast", "dvzero_lr5e-4"),
    "mastlrAVdvzA": ("mast_lr1e-3", "dvzero_lr1e-3"), "mastlrBVdvz": ("mast_lr2e-3", "dvzero_lr2e-3"),
    "mastVdvcaa": ("mast", "dvcaa_lr5e-4"),
}
PM = r"$\pm$"


def pm(mean, sd, nd=1):
    return f"{mean:.{nd}f}{PM}{sd:.{nd}f}"


def load_judged(path: Path):
    return agg.load_items(path) if path.exists() else None


def rate_list(list_of_items):
    """Per-run rates -> mean/sd dict for each metric."""
    rs = [agg.rates(it) for it in list_of_items if it]
    if not rs:
        return None
    out = {}
    for k in ("truth", "info", "ti_product", "ti_conj"):
        v = np.array([r[k] for r in rs])
        out[k] = (float(v.mean()), float(v.std(ddof=1)) if len(v) > 1 else 0.0)
    out["n"] = len(rs)
    return out


class Numbers:
    def __init__(self):
        self.lines = []

    def set(self, key, metric, value):
        self.lines.append(f"\\setres{{{key}}}{{{metric}}}{{{value}}}")

    def write(self, path: Path):
        path.write_text("% generated by scripts/make_paper_numbers.py -- do not edit\n" + "\n".join(self.lines) + "\n")


def main_table(num: Numbers, judge: str):
    agg.JUDGE_FILE = "gpt_judge_results.json" if judge == "gpt" else "open_judge_results.json"
    runs = agg.discover()
    table = agg.summarise(runs)
    prefix = "" if judge == "gpt" else "o"
    for key, m in KEYS.items():
        r = table.get(m)
        if not r or "ti_product" not in r:
            continue
        if judge == "gpt":
            for metric, k in (("truth", "truth"), ("info", "info"), ("tiprod", "ti_product"), ("ticonj", "ti_conj")):
                num.set(key, metric, pm(r[k]["mean"], r[k]["sd"]))
            num.set(key, "sdtiprod", f"{r['ti_product']['sd']:.1f}")
            num.set(key, "nseeds", str(r["n_seeds_full"]))
            if "baseline" in table and "ti_product" in table["baseline"]:
                num.set(key, "gainbase", f"{r['ti_product']['mean'] - table['baseline']['ti_product']['mean']:+.1f}")
        else:
            num.set(key, "otiprod", pm(r["ti_product"]["mean"], r["ti_product"]["sd"]))
            num.set(key, "oticonj", pm(r["ti_conj"]["mean"], r["ti_conj"]["sd"]))
    if judge != "gpt":
        return runs, table
    for key, (a, b) in COMPARE.items():
        if a in table and b in table:
            w = agg.wins(table, a, b, key="ti_product")
            num.set(key, "cells", f"{w['a_wins']}/{w['cells']}")
            bs = agg.paired_bootstrap(runs, a, b)
            if bs:
                num.set(key, "diff", f"{bs['diff_product']:+.1f}")
                num.set(key, "ci", f"{bs['ci95_product'][0]:+.1f}, {bs['ci95_product'][1]:+.1f}")
                num.set(key, "diffconj", f"{bs['diff_conj']:+.1f}")
    if "dvzero_lr5e-4" in table and "dvcaa_lr5e-4" in table:
        g = abs(table["dvzero_lr5e-4"]["ti_product"]["mean"] - table["dvcaa_lr5e-4"]["ti_product"]["mean"])
        num.set("dvinit", "gap", f"{g:.1f}")
    # fold-1-only MAST for the noise ablation comparison
    f1 = rate_list([runs["mast"][s][1] for s in runs.get("mast", {}) if 1 in runs["mast"][s]])
    if f1:
        num.set("mastfA", "tiprod", pm(*f1["ti_product"]))
    # MC1/MC2
    mc = agg.mc_results()
    for name, key in (("baseline", "base"), ("mast", "mast"), ("raw_caa", "caa1"), ("dvzero_lr2e-3:dvzero", "dvzero")):
        for task, metric in (("truthfulqa_mc1", "mcone"), ("truthfulqa_mc2", "mctwo")):
            if name in mc and task in mc[name]:
                num.set(key, metric, pm(mc[name][task]["mean"], mc[name][task]["sd"]))
    return runs, table


def noise_ablation(num: Numbers, judge_file: str):
    """3 seeds of fold 1 (noise input) vs MAST on the same folds, same judge."""
    noise, mast = [], []
    for s in (42, 123, 456):
        noise.append(load_judged(OUT / f"rcv_noise_s{s}/fold1/mlp_mc/scale_1.00/{judge_file}"))
        mast.append(load_judged(OUT / f"rcv_main_s{s}/fold1/mlp_mc/scale_1.00/{judge_file}"))
    rn, rm = rate_list(noise), rate_list(mast)
    if rn:
        num.set("noise", "tiprod", pm(*rn["ti_product"]))
        num.set("noise", "nseeds", str(rn["n"]))
    if rm and judge_file.startswith("open"):
        num.set("mastfA", "tiprod", pm(*rm["ti_product"]))


def cathold(num: Numbers, paper_dir: Path, judge_file: str):
    rows = []
    for fold in ("A", "B"):
        dirs = [OUT / f"cathold_fold_{fold}"] + [OUT / f"rcathold_{fold}_ts{t}" for t in (123, 456)]
        res = {}
        for var, sc in (("baseline", "scale_0.00"), ("steered", "scale_1.00"), ("mlp_mc", "scale_1.00")):
            res[var] = rate_list([load_judged(d / var / sc / judge_file) for d in dirs])
        if res["mlp_mc"]:
            num.set(f"cat{fold}", "base", pm(*res["baseline"]["ti_product"]) if res["baseline"] else "--")
            num.set(f"cat{fold}", "mast", pm(*res["mlp_mc"]["ti_product"]))
            num.set(f"cat{fold}", "seeds", str(res["mlp_mc"]["n"]))
            rows.append((fold, res))
    judge_name = "GPT-4o-mini" if judge_file.startswith("gpt") else "AllenAI"
    lines = [r"\begin{table}[h]\centering\small\setlength{\tabcolsep}{3pt}",
             r"\begin{tabular}{lccc}\toprule",
             r"Unseen categories & Unsteered & Raw CAA & \textsc{MAST} \\ \midrule"]
    for fold, res in rows:
        g = lambda v: pm(*res[v]["ti_product"]) if res[v] else "--"  # noqa: E731
        lines.append(f"Fold {fold} & {g('baseline')} & {g('steered')} & {g('mlp_mc')} \\\\")
    lines += [r"\bottomrule\end{tabular}",
              rf"\caption{{Category hold-out: T$\times$I on test categories never seen in training "
              rf"({judge_name} judges; mean $\pm$ s.d.\ over {rows[0][1]['mlp_mc']['n'] if rows else 0} torch seeds; the category split is fixed).}}",
              r"\label{tab:cathold}\end{table}"]
    (paper_dir / "cathold_table.tex").write_text("\n".join(lines) + "\n")


def gemma(num: Numbers, paper_dir: Path):
    jf = "gpt_judge_results.json"
    fold1 = OUT / "g4b_bn8_full"
    fold2 = OUT / "rcv_g4bmain_s42" / "fold2"
    out = {}
    for var, sc, key in (("baseline", "scale_0.00", "gemmaBase"), ("steered", "scale_1.00", "gemmaCaa"),
                         ("mlp_mc", "scale_1.00", "gemmaMast")):
        a, b = load_judged(fold1 / var / sc / jf), load_judged(fold2 / var / sc / jf)
        if a and b:
            r = agg.rates(a + b)
            out[key] = r
            num.set(key, "tiprod", f"{r['ti_product']:.1f}")
            num.set(key, "info", f"{r['info']:.1f}")
            num.set(key, "ticonj", f"{r['ti_conj']:.1f}")
    # extra torch seeds on fold 1 (per-item metrics were what we had for these runs)
    seeds = rate_list([load_judged(OUT / d / "mlp_mc/scale_1.00" / jf) for d in ("g4b_bn8_full", "g4b_bn8_s123", "g4b_bn8_s456")])
    if seeds:
        num.set("gemmaMastSeeds", "tiprod", pm(*seeds["ti_product"]))
    dv = {}
    for init, lr, key in (("zero", "5e-4", "gemmaDvLow"), ("zero", "2e-3", "gemmaDvMid"),
                          ("zero", "5e-3", "gemmaDvHigh"), ("caa", "5e-4", "gemmaDvCaa")):
        it = load_judged(OUT / f"rg4b_dv{init}_lr{lr}_s42/fold1/mlp_mc/scale_1.00/{jf}")
        if it:
            r = agg.rates(it)
            dv[key] = (init, lr, r)
            num.set(key, "tiprod", f"{r['ti_product']:.1f}")
            num.set(key, "info", f"{r['info']:.1f}")
    lines = [r"\begin{table}[h]\centering\small\setlength{\tabcolsep}{3pt}",
             r"\begin{tabular}{lccc}\toprule", r"Gemma-3-4B-IT, layer 13 & Truth & Info & T$\times$I \\ \midrule"]
    names = {"gemmaBase": "Unsteered", "gemmaCaa": r"Raw CAA ($\alpha{=}1$)", "gemmaMast": r"\textsc{MAST} (lr $5{\times}10^{-4}$)"}
    for key, r in out.items():
        lines.append(f"{names[key]} (2-fold, seed 42) & {r['truth']:.1f} & {r['info']:.1f} & {r['ti_product']:.1f} \\\\")
    if seeds:
        lines.append(rf"\textsc{{MAST}}, fold 1, 3 torch seeds & {pm(*seeds['truth'])} & {pm(*seeds['info'])} & {pm(*seeds['ti_product'])} \\")
    for key, (init, lr, r) in dv.items():
        lines.append(f"Direct vector, {init} init, lr {lr} (fold 1) & {r['truth']:.1f} & {r['info']:.1f} & {r['ti_product']:.1f} \\\\")
    lines += [r"\bottomrule\end{tabular}",
              r"\caption{Gemma-3-4B-IT with the unchanged LLaMA recipe (GPT-4o-mini judges).}\label{tab:gemma}\end{table}"]
    (paper_dir / "gemma_table.tex").write_text("\n".join(lines) + "\n")


def lr_outputs(table, runs, paper_dir: Path):
    curves = {
        r"\textsc{MAST}": {"5e-4": "mast", "1e-3": "mast_lr1e-3", "2e-3": "mast_lr2e-3"},
        "Direct vector, zero init": {"5e-4": "dvzero_lr5e-4", "1e-3": "dvzero_lr1e-3",
                                     "2e-3": "dvzero_lr2e-3", "5e-3": "dvzero_lr5e-3"},
        "Direct vector, CAA init": {"5e-4": "dvcaa_lr5e-4", "2e-3": "dvcaa_lr2e-3"},
    }
    train_loss = defaultdict(list)  # method -> final-10-step mean training loss per cell
    for d in OUT.glob("rcv_*_s*/fold*"):
        m = agg.RCV.match(d.parent.name)
        h = d / "training_history.json"
        if not m or not h.exists():
            continue
        hist = json.loads(h.read_text())
        loss = hist.get("mc", {}).get("loss") or hist.get("mc", {}).get("losses")
        if isinstance(hist.get("mc"), list):
            loss = [x.get("loss") for x in hist["mc"] if isinstance(x, dict)]
        if loss:
            name = "mast" if m["method"] == "main" else m["method"]
            train_loss[name].append(float(np.mean([x for x in loss[-10:] if x is not None])))

    lines = [r"\begin{table}[h]\centering\small\setlength{\tabcolsep}{2.5pt}",
             r"\resizebox{\columnwidth}{!}{%", r"\begin{tabular}{llcccc}\toprule",
             r"Method & lr & Truth & Info & T$\times$I & Train loss \\ \midrule"]
    for label, pts in curves.items():
        for lr, m in pts.items():
            r = table.get(m)
            if not r or "ti_product" not in r:
                continue
            tl = f"{np.mean(train_loss[m]):.2f}" if train_loss.get(m) else "--"
            lines.append(f"{label} & {lr} & {pm(r['truth']['mean'], r['truth']['sd'])} & "
                         f"{pm(r['info']['mean'], r['info']['sd'])} & {pm(r['ti_product']['mean'], r['ti_product']['sd'])} & {tl} \\\\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}}",
              r"\caption{\textsc{MAST} and the directly optimised vector across learning rates (2-fold CV, mean $\pm$ s.d.\ over 3 seeds; "
              r"GPT-4o-mini judges). Train loss: mean of the last 10 of 100 steps (margin loss + anchor), averaged over cells.}",
              r"\label{tab:lr}\end{table}"]
    (paper_dir / "lr_table.tex").write_text("\n".join(lines) + "\n")

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    lrs = {"5e-4": 5e-4, "1e-3": 1e-3, "2e-3": 2e-3, "5e-3": 5e-3}
    style = {r"\textsc{MAST}": ("#1f5fa8", "o"), "Direct vector, zero init": ("#c0392b", "s"),
             "Direct vector, CAA init": ("#e08a2c", "^")}
    fig, axes = plt.subplots(2, 1, figsize=(3.4, 3.6), sharex=True, gridspec_kw={"height_ratios": [1.6, 1]})
    for label, pts in curves.items():
        xs, ti, tis, info, infos = [], [], [], [], []
        for lr, m in pts.items():
            r = table.get(m)
            if r and "ti_product" in r:
                xs.append(lrs[lr]); ti.append(r["ti_product"]["mean"]); tis.append(r["ti_product"]["sd"])
                info.append(r["info"]["mean"]); infos.append(r["info"]["sd"])
        if not xs:
            continue
        c, mk = style[label]
        name = label.replace(r"\textsc{MAST}", "MAST")
        axes[0].errorbar(xs, ti, yerr=tis, color=c, marker=mk, ms=4, lw=1.5, capsize=2, label=name)
        axes[1].errorbar(xs, info, yerr=infos, color=c, marker=mk, ms=4, lw=1.5, capsize=2)
    if "caa_a2" in table and "ti_product" in table["caa_a2"]:
        axes[0].axhline(table["caa_a2"]["ti_product"]["mean"], color="grey", ls=":", lw=1)
        axes[0].text(5.2e-4, table["caa_a2"]["ti_product"]["mean"] + 0.6, "raw CAA (tuned)", fontsize=6.5, color="grey")
    axes[0].set_ylabel("True×Info (%)", fontsize=8)
    axes[1].set_ylabel("Info (%)", fontsize=8)
    axes[1].set_xscale("log")
    axes[1].set_xticks(list(lrs.values()))
    axes[1].set_xticklabels(list(lrs.keys()), fontsize=7)
    axes[1].set_xlabel("learning rate", fontsize=8)
    for ax in axes:
        ax.tick_params(labelsize=7)
        ax.spines[["top", "right"]].set_visible(False)
        ax.grid(alpha=0.25, lw=0.5)
    axes[0].legend(fontsize=6.5, frameon=False, loc="lower right")
    fig.tight_layout(h_pad=0.4)
    (paper_dir / "figures").mkdir(exist_ok=True)
    fig.savefig(paper_dir / "figures" / "lr_sweep.pdf")
    plt.close(fig)


def categories(runs, paper_dir: Path):
    cats = agg.categories(runs, ["baseline", "caa_a2", "dvzero_lr2e-3", "mast"])
    if "mast" not in cats:
        return
    nseed = max(len(runs["mast"]), 1)
    lines = [r"\begin{table*}[t]\centering\small\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{lrcccc}\toprule",
             r"Category & $n$ & Unsteered & Raw CAA ($\alpha{=}2$) & Direct vector (tuned lr) & \textsc{MAST} \\ \midrule"]
    for c, r in sorted(cats["mast"].items(), key=lambda kv: -kv[1]["ti_conj"]):
        g = lambda m: f"{cats[m][c]['ti_conj']:.1f}" if m in cats and c in cats[m] else "--"  # noqa: E731
        lines.append(f"{c} & {r['n'] // nseed} & {g('baseline')} & {g('caa_a2')} & {g('dvzero_lr2e-3')} & {g('mast')} \\\\")
    lines += [r"\bottomrule\end{tabular}",
              rf"\caption{{Per-category T$\wedge$I (\%), LLaMA-2-7B-Chat, all 817 questions answered once per seed by 2-fold CV and "
              rf"pooled over {nseed} seeds (GPT-4o-mini judges); $n$ = questions per category. Sorted by \textsc{{MAST}}.}}",
              r"\label{tab:categories}\end{table*}"]
    (paper_dir / "categories_table.tex").write_text("\n".join(lines) + "\n")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--paper-dir", type=Path, default=Path("paper/drafts/revision_oct2026/paper"))
    args = p.parse_args()
    num = Numbers()
    runs, table = main_table(num, "gpt")
    main_table(num, "open")
    noise_ablation(num, "open_judge_results.json")
    cathold(num, args.paper_dir, "open_judge_results.json")
    gemma(num, args.paper_dir)
    if table:
        lr_outputs(table, runs, args.paper_dir)
        categories(runs, args.paper_dir)
    num.write(args.paper_dir / "numbers.tex")
    print(f"wrote {len(num.lines)} macros to {args.paper_dir / 'numbers.tex'}")


if __name__ == "__main__":
    main()
